version: "3.7"

services:

    backend:
       
        build: ./
        
        ports: 
            - 3000:3000
        
        depends_on:
            - mongodb    
            
        environment:
            WAIT_HOSTS: mongodb://127.0.0.1:27017/
            MONGODB_URI: mongodb://127.0.0.1:27017/
            OPENEO_URI : http://ccceocubes_con:8000
            
      

    mongodb:
        image: mongo
        restart: always
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
             - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
             - ./mongo-volume:/data/db

        command: mongod --noauth 
        
        
    
    mong-express:
        image: mongo-express
        restart: always
        
        depends_on:
            - mongodb
        ports: 
            - '8081:8081'

    ccceocubes_con:
        image: kwundram/ccceocubes:b8
        environment:
        - AWSHOST=34.209.215.214
        - TZ=Etc/UTC
        - DEBIAN_FRONTEND=noninteractive
        ports:
            - "8000:8000"
        restart: always
    
    