version: "3.7"

services:

    frontend:
        build: ./views
        ports:
            - 3000:3000



    backend:
        build: ./bin
        ports: 
            - 3000:3001
        environment:

    db:
    
            



volumes: