version: "3.7"

services:

    backend:
       
        build: ./
        
        ports: 
            - 3000:3000
        
        
        depends_on:
            - mongodb
            - ccceocubes_con
            
        environment:
            WAIT_HOSTS: mongodb://mongodb:27017/
            MONGODB_URI: mongodb://mongodb:27017/
            OPENEO_URI : http://ccceocubes_con:8000
        networks:
            - ccc_network
            
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
             - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
             - ./mongo-volume:/data/db

        command: mongod --noauth 
        networks:
            - ccc_network
        

    ccceocubes_con:
        image: kwundram/ccceocubes:b13
        container_name: ccceocubes_con
        environment:
        - AWSHOST=34.209.215.214
        - TZ=Etc/UTC
        - DEBIAN_FRONTEND=noninteractive
        ports:
            - "8000:8000"
              
        restart: always
        networks:
            - ccc_network

networks:
  ccc_network:  
    driver: bridge

volumes:
    mongo-init:
    mongo-volume:
    